#ifndef UART_H_
#define UART_H_


#define UART_RX_FIFO_LENGTH (1 << 7)  // 2^7 = 128
#define UART_DATA_BUFFER_LENGTH (70)
#define UART_TX_BUFFER_LENGTH (103)

enum UARTPort {
  UART_PORT_UART0 = 0,
  UART_PORT_UART1,
  UART_PORT_UART2,
};

enum UARTRxMode {
  UART_RX_MODE_IDLE = 0,
  UART_RX_MODE_MK_ONGOING,
  UART_RX_MODE_UT_ONGOING,
};


#endif  // UART_H_
